### ISSUE TITLE
bug 冒険者アカデミーの受付員エーラから分厚い戦闘教範を何回でも受け取れてしまう

### ISSUE THREAD

**Issue by niconicop** [auriga/auriga#1]
OS: ubuntu

**Comment by niconicop** [comment]
quest.hの　#define MAX_QUEST_DB　を増やしたらなおりました

**Comment by Lamina-Cocoa** [comment]
独自にクエスト追加してますか？

**Comment by niconicop** [comment]
独自にクエストは追加していません、ほぼバニラ状態です。
quest_db.txtを見ると1981行あるので、定義されているMAX_QUEST_DBの1500を超えていると思います。

**Comment by refis** [comment]
Patch 1299にて修正対応させていただきました！
ご報告ありがとうございます！
