### ISSUE TITLE
2018-04-18パケット定義抜け

### ISSUE THREAD

**Issue by eni-ro** [auriga/auriga#10]
2018-04-18クライアント対応ありがとうございました
早速使ってみたところ、消費アイテム使用のパケット定義が抜けているようです
`db\packet_db.lua`の3135行目に以下の定義を追加したら、アイテムを使用できたので報告まで
```
p(0x0439,8,"useitem",{2,6})
```

**Comment by refis** [comment]
すっぽぬけていましたね！
20080827以降固定のようなので、2347行目に追加するよう対応します！

**Comment by eni-ro** [comment]
修正ありがとうございます！

**Comment by refis** [comment]
ご報告ありがとうございました！
