### ISSUE TITLE
ニューマ範囲外に出た際の処理

### ISSUE THREAD

**Issue by eni-ro** [auriga/auriga#11]
不具合かどうか判断がつかなかったのですけれど、一応報告させて頂きます。

モブが移動してニューマ範囲外に出た際の処理が実行されていないように思えます。
具体的には、モブがニューマを自分がいるセルに使用した後にニューマの範囲外に移動しても、状態異常のタイマクリア処理が実行されておらず、遠距離無効になったままの気がします。
SSはマーガレッタ=ソリン(転生二次職)をsummonで召喚して弓で攻撃したものですけれど、プレイヤー頭上でニューマを使用後SSの位置まで移動していても攻撃がミスになり続けます。
![ニューマ](https://user-images.githubusercontent.com/59181965/75101125-1aaef200-561b-11ea-95c7-8e87063641ae.jpg)

私の環境で確認した限りでは、`skill_unit_move_sub`関数において、ニューマの'group->interval'が100になっているため即returnしてしまい、`skill_unit_onout`関数が実行されないのが原因な気します
Patch1325 04b93913dff2769f9df0068b245cfcbeb7321de8 で設定が-1から100に変わっており、仕様なのか判断が付きませんでした。

お時間があるときで結構ですので、ご確認お願いします。

**Comment by refis** [comment]
現在のユニット周りの処理上、即座に効果を打ち消すのは難しいので、
Patch1389にてinterval+100msで継ぎ足し更新するように修正しました。
違和感を感じるほどではないと思いますが、確認してみてください。
レポートありがとうございます！

**Comment by eni-ro** [comment]
正常に動作すること確認しました。
いつも素早い対応、本当にありがとうございます。
