### ISSUE TITLE
タロウの傷使用時のヌルポインタアクセス

### ISSUE THREAD

**Issue by eni-ro** [auriga/auriga#12]
`status_change_start` 関数でタロウの傷の状態異常のマップ制限を行っていますけれど、`sd`のヌルポチェックが無いため、メモリアクセス違反が発生してしまうようです。
`sd`が何かは正確に把握していませんが、下記のように変更してマップサーバーが落ちないことは確認済みです。

変更前
```
if(type == SC_BITESCAR && !map[sd->bl.m].flag.pvp && !map[sd->bl.m].flag.gvg && !map[sd->bl.m].flag.turbo)
```
変更後
```
if(type == SC_BITESCAR && sd && !map[sd->bl.m].flag.pvp && !map[sd->bl.m].flag.gvg && !map[sd->bl.m].flag.turbo)
```

**Comment by refis** [comment]
sdではなくblからマップ情報を呼び出すようにPatch1389にて修正いたしました！
レポートありがとうございます！

**Comment by eni-ro** [comment]
こちらも対応ありがとうございました。
自分の直し方が意図通りではないようなので、移植させて頂きます！
