### ISSUE TITLE
GitHub Actions CIの導入

### ISSUE THREAD

**Issue by gorockn** [auriga/auriga#25]
ふと久々にこちらのリポジトリの存在を思い出し、Ubuntu 22.04 + VSCodeでビルド・デバッグ実行しようとしたところ、コンパイルエラーになってしまいました。
近頃はGitHub Actions CIが便利なので、GitHub Actions CI対応プルリクを提出しようかなと思っているのですが、 メンテナの皆様、いかがでしょうか？

タスクリスト

- [x] Windowsビルド(MSVC 2022)対応
  - https://github.com/auriga/auriga/pull/26
- [x] Windowsビルド(MSVC 2019)対応
  - https://github.com/auriga/auriga/pull/27
- [x] Linuxビルド(GCC)対応
  - https://github.com/auriga/auriga/pull/28
- [x] MacOSビルド(GCC)対応
  - MacOSは標準でGCCインストールされていないので本イシューのゴールから除外
- [x] Windowsビルド(MinGW)対応
  - 別途メタビルドシステム導入が必要なので本イシューのゴールから除外
- [x] Linuxビルド(Clang)対応
  - Makefile修正 or 別途メタビルドシステム導入が必要なので本イシューのゴールから除外
- [x] MacOSビルド(Clang)対応
  - https://github.com/auriga/auriga/pull/29

**Comment by gorockn** [comment]
上記ですが、Ubuntu 22.04環境のコンパイルエラー解消時にWindowsビルドが壊れていないかを確認する事が目的です。
GitHub Actions CIでやろうと思っているのは以下の通りです。

- Windows / MacOS / LinuxのビルドCI
  - Windowsの場合はMSVC / MSYS + MinGW
  - MacOS / LinuxはGCC / Clang
- MacOS / LinuxについてはGitHub Actions CacheでCCache対応（ビルド高速化）
  - Windowsで似たようなツールありそうな気がしているのですが、ちゃんと調べられていないです...

おそらくMacOS / LinuxのCIは現状だとFAILになっちゃうと思いますが、Windowsビルド状況見ながら細かくプルリクだそうかな、と思ってます。

（ついでにLLVMの周辺ツール + ReviewDogなどモダンなツールも導入して、レビュアー負担下げられると尚良さそう、なども考えております）

**Comment by refis** [comment]
チェックが行き届いてない部分が多いので、対応していただけると大変うれしいです！と私は思ってます！

**Comment by Lamina-Cocoa** [comment]
Github Actionsの導入は考えていたので歓迎です。
（私は使ったことがないのでどうやって使うのか調べるところから始まるので）

**Comment by gorockn** [comment]
承知しました！
歓迎頂けて良かったです :smile: 

今後の流れですが、以下の手順で進めていこうと思ってます。

1. Windowsビルド(MSVC)対応
2. Linuxビルド(GCC)対応
3. MacOSビルド(GCC)対応
4. Windowsビルド(MinGW)対応
5. Linuxビルド(Clang)対応
6. MacOSビルド(Clang)対応

本イシューのゴールとしては6まで対応完了したらクローズ、GitHub Actions CIを導入することを優先して、1以外はFAIL前提で考えています。
（少なくともUbuntu 22.04 / GCC 11だと、GCCオプションの修正や、Cコードの修正しないと、コンパイルエラーになっちゃうのは確定っぽいので...）

プルリク提出していく過程で、気になる所や、こうすればもっと良くなる、みたいなお話があれば、適宜コメント頂けると幸いです :pray: 
よろしくお願いします〜

**Comment by gorockn** [comment]
すいません、CI調整していたらめっちゃリンク飛んじゃいました...orz
簡単なGitHub Actions CI動いたので、プルリク提出しました。
お手すきの際にご確認ください :pray:

**Comment by Lamina-Cocoa** [comment]
Mergeしましたー、ありがとうございます。

**Comment by gorockn** [comment]
ありがとうございました！
こちらのイシューは役目を終えたので、クローズさせていただきます。
