### ISSUE TITLE
vc_make.batの対応コンパイラ整理

### ISSUE THREAD

**Issue by Lamina-Cocoa** [auriga/auriga#3]
現在Visual C++ 6.0から対応になってますが、そもそもVisual C++ 6.0の対応OSがWindows XPとWindows Server 2003（それ以前のは論外）なので見直しが必要ではないでしょうか。

開発ツール対応 OS 一覧
https://www.microsoft.com/ja-jp/dev/support/tools.aspx

このページにあるOS一覧ではWindows XP、Windows Server 2003、Windows Vistaが延長サポートまで切れています。
それに合わせてVisual C++6.0、Visual Studio .NET 2002、Visual Studio .NET 2003はAurigaでもサポート切っていいと思っています。

問題はVisual Studio 2005、2008をサポートするかどうかです。
と言うのもこの2つのバージョンは開発陣の手元にないです、多分。
AppVeyorではVM上にWindows 10を立てているので対応していないため当然ありません。
私としては最新OSに対応するコンパイラのみでいいのではないかと考えています。

参考までに各OSのサポート期限です。
* Windows Server 2008
メインストリーム サポート終了日: 2015年1月13日
延長サポート終了日: 2020年1月14日

* Windows Server 2008 R2
メインストリーム サポート終了日: 2015年1月13日
延長サポート終了日: 2020年1月14日

* Windows 7
メインストリーム サポート終了日:2015年1月13日
延長サポート終了日:2020年1月14日

* Windows Server 2012
メインストリーム サポート終了日: 2018年1月9日
延長サポート終了日: 2023年1月10日

* Windows Server 2012 R2
メインストリーム サポート終了日:2018年1月9日
延長サポート終了日:2023年1月10日

* Windows 8
サービスパック サポート終了日:2016年1月12日

* Windows 8.1
メインストリーム サポート終了日:2018年1月9日
延長サポート終了日:2023年1月10日

**Comment by Lamina-Cocoa** [comment]
Visual Studio自体のライフサイクルで見るべきだった。
https://support.microsoft.com/ja-jp/lifecycle/search?alpha=Visual%20Studio
（わかりにくい）

* Visual Studio 2010
メインストリーム サポート終了日:2015年07月14日？

* Visual Studio 2012
メインストリーム サポート終了日:2018年01月09日？ 

* Visual Studio 2013
メインストリーム サポート終了日:2019年04月09日？

* Visual Studio 2015
メインストリーム サポート終了日:2020年10月13日？

**Comment by mcrx2** [comment]
別のIssue立てたほうがいいのかもしれませんが…。
vc_make.batを見直すのであれば、以下の記述も見直していただけないでしょうか。
```bat
rem R化前のシステムを使う場合はコメントアウトをはずす
set __PRE_RENEWAL__=/D "PRE_RENEWAL"
```
明確な理由があってPre-Renewalがデフォルトになっているのなら、それはそれで構わないのですが。

**Comment by Kurosawa0626** [comment]
R化実装開始時に全部実装出来てないって状況だったのでR化前がデフォになってますが、
流石にもうR化後をデフォにしていいですね。

**Comment by refis** [comment]
Renewalへの対応が完了してから(≠最新データというわけではない)変更しようとは思っていたのですが、タイミングを見失っていただけです…

**Comment by mcrx2** [comment]
そういうことでしたか。状況は理解しました。

**Comment by Lamina-Cocoa** [comment]
古いのは切ったのでclose
