### ISSUE TITLE
mob_avail使用時の配列外参照

### ISSUE THREAD

**Issue by eni-ro** [auriga/auriga#8]
mob.cのmob_readdb_mobavail関数において、PCキャラ変換の設定を行うと配列外参照が発生して起動時にクラッシュします。
引数の数が16個で最終処理でstr[15]でアクセスすることから、下記の定数15は16の間違いだと思います。
```
char *str[15],*p,*np;
for(j=0,p=line;j<15;j++){
```

**Comment by refis** [comment]
ご報告ありがとうございます。
Patch 1372にて修正を取り込ませていただきました！
